name: Auto-update Tailscale (stable)

on:
  schedule:
    - cron: "15 2 * * *" # Diario 02:15 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Detect addon directory (root or subfolder)
        id: paths
        run: |
          set -e
          # Si tu add-on está en la raíz:
          if [ -f "Dockerfile" ] && [ -f "config.yaml" ]; then
            echo "dir=." >> $GITHUB_OUTPUT
          # Si está en una carpeta típica:
          elif [ -f "tailscale_nodalia/Dockerfile" ] && [ -f "tailscale_nodalia/config.yaml" ]; then
            echo "dir=tailscale_nodalia" >> $GITHUB_OUTPUT
          elif [ -f "tailscale/Dockerfile" ] && [ -f "tailscale/config.yaml" ]; then
            echo "dir=tailscale" >> $GITHUB_OUTPUT
          else
            echo "No encuentro Dockerfile+config.yaml (ni en root, ni tailscale_nodalia/, ni tailscale/)"
            exit 1
          fi

      - name: Get latest stable Tailscale version (GitHub Releases)
        id: ts
        run: |
          set -e
          # /releases/latest -> última release estable (no prerelease / no draft)
          LATEST_TAG=$(curl -s https://api.github.com/repos/tailscale/tailscale/releases/latest | jq -r .tag_name)
          if [ -z "$LATEST_TAG" ] || [ "$LATEST_TAG" = "null" ]; then
            echo "No pude obtener tag_name de Tailscale."
            exit 1
          fi
          echo "latest=${LATEST_TAG}" >> $GITHUB_OUTPUT

      - name: Read current TAILSCALE_VERSION from Dockerfile
        id: cur
        run: |
          set -e
          DIR="${{ steps.paths.outputs.dir }}"
          if ! grep -qE '^ARG TAILSCALE_VERSION=' "${DIR}/Dockerfile"; then
            echo "No existe 'ARG TAILSCALE_VERSION=' en ${DIR}/Dockerfile"
            exit 1
          fi
          CURRENT=$(grep -E '^ARG TAILSCALE_VERSION=' "${DIR}/Dockerfile" | sed -E 's/ARG TAILSCALE_VERSION="([^"]+)"/\1/')
          echo "current=${CURRENT}" >> $GITHUB_OUTPUT

      - name: Check if update needed
        id: check
        run: |
          if [ "${{ steps.ts.outputs.latest }}" != "${{ steps.cur.outputs.current }}" ]; then
            echo "needs_update=true" >> $GITHUB_OUTPUT
          else
            echo "needs_update=false" >> $GITHUB_OUTPUT
          fi

      - name: Update Dockerfile TAILSCALE_VERSION
        if: steps.check.outputs.needs_update == 'true'
        run: |
          set -e
          DIR="${{ steps.paths.outputs.dir }}"
          LATEST="${{ steps.ts.outputs.latest }}"
          sed -i -E "s/^ARG TAILSCALE_VERSION=\"[^\"]+\"/ARG TAILSCALE_VERSION=\"${LATEST}\"/" "${DIR}/Dockerfile"
          echo "Dockerfile actualizado a ${LATEST}"

      - name: Bump addon version (minor, reset patch)
        if: steps.check.outputs.needs_update == 'true'
        id: bump
        run: |
          set -e
          DIR="${{ steps.paths.outputs.dir }}"
          CURRENT_VER=$(grep -E '^version:' "${DIR}/config.yaml" | awk '{print $2}')

          # bump minor: X.Y.Z -> X.(Y+1).0
          NEW_VER=$(python3 - << 'PY'
import re, sys
v = sys.argv[1].strip()
m = re.match(r'^(\d+)\.(\d+)\.(\d+)$', v)
if not m:
    raise SystemExit(f"Version no valida en config.yaml: {v}")
x, y, z = map(int, m.groups())
print(f"{x}.{y+1}.0")
PY
"${CURRENT_VER}")

          sed -i -E "s/^version: .*/version: ${NEW_VER}/" "${DIR}/config.yaml"
          echo "Bump version: ${CURRENT_VER} -> ${NEW_VER}"
          echo "new_ver=${NEW_VER}" >> $GITHUB_OUTPUT

      - name: Commit & push
        if: steps.check.outputs.needs_update == 'true'
        run: |
          set -e
          DIR="${{ steps.paths.outputs.dir }}"
          LATEST="${{ steps.ts.outputs.latest }}"
          NEW_VER="${{ steps.bump.outputs.new_ver }}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "${DIR}/Dockerfile" "${DIR}/config.yaml"
          git commit -m "chore: bump Tailscale to ${LATEST} (addon ${NEW_VER})"
          git push

      - name: No update needed
        if: steps.check.outputs.needs_update != 'true'
        run: echo "Tailscale ya está en la última estable: ${{ steps.cur.outputs.current }}"
